"""Описание изменений

Revision ID: 3103faca8afa
Revises: a8bcc3d44f9c
Create Date: 2024-11-27 17:41:12.432171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3103faca8afa'
down_revision = 'a8bcc3d44f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('file_info', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('extension',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('path_file',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_info', schema=None) as batch_op:
        batch_op.alter_column('path_file',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('extension',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
