"""sec migrations

Revision ID: a8bcc3d44f9c
Revises: 0feb522e1d2b
Create Date: 2024-11-26 10:12:03.157027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bcc3d44f9c'
down_revision = '0feb522e1d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('path_file', sa.String(length=300), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_info')
    # ### end Alembic commands ###
